### ISSUE TITLE
import error on installation

### ISSUE THREAD

**Issue by jostyee** [yeraydiazdiaz/sublime-rest-client#16]
```
unloading plugin REST Client.plugin
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
generating syntax summary
ignored packages updated to: ["Markdown", "Rust", "Six", "Vintage", "Vintageous"]
reloading plugin REST Client.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 312, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 808, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/yee/Library/Application Support/Sublime Text/Installed Packages/REST Client.sublime-package/plugin.py", line 15, in <module>
ImportError: cannot import name 'Response' from 'REST Client.rest_client' (/Users/yee/Library/Application Support/Sublime Text/Installed Packages/REST Client.sublime-package/rest_client/__init__.py)
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
generating syntax summary
reloading settings Packages/User/Preferences.sublime-settings
```

my system environment:
```
❯ pip list|grep request
requests                 2.27.1
```

Do I need to upgrade manually before install the package?

**Comment by yeraydiazdiaz** [comment]
Hi @jostyee, Sublime REST Client works independently from your system environment, it should "Just Work".

I see you're on Mac OS X, I just installed REST Client and performed requests with no problems.

Can you try uninstalling and reinstalling REST Client and attempting a simple request like:

```
GET https://httpbin.org/get
```

and see if you get a response?

**Comment by jostyee** [comment]
Sorry, I can find REST Client in package list but there're no related options in command palette.

btw, this package name is so confusing that I couldn't use `Install Package` to install, had to choose `Advanced Install Package`.

**Comment by yeraydiazdiaz** [comment]
I'm having trouble understanding your issue.

The project's name is "REST Client" and to install it you simply need to use `Install Package` and search for `REST Client`, it should be the top choice, you can verify the URL in the search result which should be https://github.com/yeraydiazdiaz/sublime-rest-client/.

You should not need to use 'related options in the command palette' or `Advanced Install Package`.

**Comment by yeraydiazdiaz** [comment]
Closing due to lack of response.
